name: Build app
on: [pull_request, push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
      
      - name: Lint
        run: ./gradlew lintDebug

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
      
      - name: Run unit tests
        run: ./gradlew test

  android_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
      
      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

  build:
    needs: [ unit_tests, android_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - name: Sign built APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload build artifact
        uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{ steps.sign_apk.outputs.signedReleaseFile }}

      - name: Upload build artifact mapping
        uses: actions/upload-artifact@master 
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt